#The admin creates a publisher account
POST http://localhost:8080/ming/admin/publisher
Accept: application/json
Content-Type: application/json

{
  "username": "Admin",
  "email": "admin@ea.com",
  "paypal": "eamoney@gmail.com",
  "publisher": "Electronic Arts",
  "country": 8,
  "password": "qwerty",
  "repeat_password": "qwerty"
}

###
#The admin sees a publisher list
GET http://localhost:8080/ming/admin/publisher
Accept: application/json

###
#The admin deletes a publisher account
DELETE http://localhost:8080/ming/admin/publisher/7
Accept: application/json
###

###
#The admin sees a games list
GET http://localhost:8080/ming/v1/games?page=1
Accept: application/json

###
#The admin edit game highlight
PUT http://localhost:8080/ming/admin/homepage/3
Accept: application/json
Content-Type: application/json

{
  "highlight": 0
}

