POST http://localhost:8080/ming/admin/publisher
Accept: application/json
Content-Type: application/json

{
  "username": "Admin",
  "email": "admin@ea.com",
  "paypal": "eamoney@gmail.com",
  "publisher": "Electronic Arts",
  "country": 8,
  "password": "qwerty",
  "repeat_password": "qwerty"
}

###
GET http://localhost:8080/ming/admin/publisher
Accept: application/json

###
DELETE http://localhost:8080/ming/admin/publisher/4
Accept: application/json
###

###
GET http://localhost:8080/ming/publisher/games
Accept: application/json

###
PUT http://localhost:8080/ming/admin/homepage/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "highlight": 1
}

