###
GET http://localhost:8080/ming/store/games/4
Accept: application/json

###
POST http://localhost:8080/ming/single/purchase/
Accept: application/json
Content-Type: application/json

{
  "idGame": 3,
  "idUser": 2
}