POST http://localhost:8080/ming/v1/publisher/1/game
Accept: application/json
Content-Type: application/json

{
  "idEsrb": 1,
  "title": "GTA10",
  "game_description": "Lo mismo pero con monas chinas",
  "size": "700GB",
  "players": 7,
  "processor": "Intel 10",
  "release_date": "2019-10-11T13:33:05.673",
  "requirements": [
    {
      "idOperatingSystem": 1,
      "processor": "Intel i9",
      "memory": "16GB RAM",
      "graphics": "GeForce 3800 ti"
    },
    {
      "idOperatingSystem": 2,
      "processor": "Intel i9",
      "memory": "16GB RAM",
      "graphics": "GeForce 3800 ti"
    }
  ],
  "memory": "15GB RAM",
  "graphics": "GeForce la chetada x2",
  "color": "#1111",
  "highlighted": 1,
  "download_path": "jaja.com",
  "images": [
    "http//11",
    "http//22",
    "http//33"
  ],
  "developer": "RockStarSdd",
  "directx": [
    1,
    2,
    3
  ],
  "operatingSystem": [
    1,
    2
  ],
  "languageGames": [
    1,
    2
  ],
  "genreGames": [
    1,
    2
  ],
  "price": 19.99,
  "sale": 10
}

### Get information game /games/{id}
GET http://localhost:8080/ming/v1/store/games/4

### 4.
GET http://localhost:8080/ming/v1/store/games/3


### Single purchase POST user's id and game's id
POST http://localhost:8080/ming/store/single/purchase/
Accept: application/json
Content-Type: application/json

{
  "idGame": 3,
  "idUser": 2
}