GET http://localhost:8080/ming/store/homepage?page=1
Accept: application/json

###
GET http://localhost:8080//ming/store/sale
Accept: application/json

###
GET http://localhost:8080//ming/store/highlights
Accept: application/json

###
GET http://localhost:8080//ming/store/releases
Accept: application/json