#The site's home page
GET http://localhost:8080/ming/v1/games?page=1
Accept: application/json

###
#The highlighted games
GET http://localhost:8080/ming/v1/games?page=1&highlight=true
Accept: application/json

###
#The games on sale
GET http://localhost:8080/ming/v1/games?page=1&sale=true
Accept: application/json

###
#The latest game releases
GET http://localhost:8080/ming/v1/games?page=1&latest=true
Accept: application/json

###
#Game Page
GET http://localhost:8080//ming/v1/store/games/2
Accept: application/json

###
#The Search Bar
GET http://localhost:8080/ming/v1/games?page=1&query=G
Accept: application/json