GET http://localhost:8080/ming/users/1
Accept: application/json
###
PUT http://localhost:8080/ming/users/7
Accept: application/json
Content-Type: application/json

{
  "alias": "el jojos",
  "email": "email@eljojos.com",
  "id_country": 5,
  "photo_path": "eljojos.com.nuevo"
}
###
PUT http://localhost:8080/ming/users/7/password
Accept: application/json
Content-Type: application/json

{
  "old_password": "newnew",
  "new_password": "newn"
}
###
GET http://localhost:8080/ming/users/2/library
Accept: application/json