GET http://localhost:8080/ming/users/2
Accept: application/json
###
PUT http://localhost:8080/ming/users/6/password
Accept: application/json
Content-Type: application/json

{
   "old_password": "nuevonuevo",
   "new_password": "nuevonuevonuevo"
}
